name: reusable workflow
on:
  workflow_call:
    inputs:
      username:
        description: 'Testing'
        required: true
        type: string
      target_env:
        description: 'Checking the env'
        required: true
        type: string
    #secrets:
      #personal_token_access:
        #required: true
jobs:
  testing-job:
    environment: ${{ inputs.target_env }}
    runs-on: ubuntu-latest
    steps:
    - name: Testing the reusable workflow
      run: echo "Hello from the reusable workflow. The value that was passed was ${{ inputs.username }}"
    - name: checking if secret is being used or not
      run: echo "${{ secrets.DB_PASSWORD }}"
    - name: Checking if variable is being used or not
      run: echo "${{ vars.DB_PORT }}"
